version: "3.8"

services:
  app:
    build: .
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - "8000:8000"
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379" 